# Generated by Django 6.0.6 on 2026-07-08 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='estado_llamada',
            field=models.CharField(default='pendiente', max_length=50),
        ),
    ]
