# Generated by Django 6.0.6 on 2026-07-09 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_estado_llamada'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='agente_extension',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
